In [2]:
import pandas as pd
#Read the dataset
mydata = pd.read_csv('C:\\Users\\saiye\Downloads\\ML ProjectTest\\diabetes.csv')
mydata.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
import numpy as np

In [6]:
#providing the input features, X= predictors,regressors, indep, variables
X = np. array(mydata[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']])
X.shape

(768, 8)

In [8]:
#providing the output feature, y: regressand, dep.variable,response variable
y = np.array(mydata['Outcome'])
y.shape

(768,)

In [9]:
#splitting the dataset into train and test datasets
#importing the train test split method
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)
X_test.shape

(231, 8)

In [13]:
#The model
#Importing the LinearRegression class
from sklearn.linear_model import LinearRegression
#Instantiation
model = LinearRegression()
#Fitting the model
mymodel = model.fit(X_train, y_train)
#K-fold Cross Validation
# Importing cross_val_score function
from sklearn.model_selection import cross_val_score
#10-fold CV
scores = cross_val_score(mymodel, X_train, y_train, scoring='r2', cv=10)
scores

array([0.18482672, 0.21996907, 0.25546072, 0.22844843, 0.37304137,
       0.24315094, 0.27150243, 0.3503144 , 0.2250272 , 0.17697749])

In [14]:
#Printting the average score
print(np.mean(scores))

0.2528718772623971


In [15]:
#Printing the scores on the test dataset
#First: Prediction
#Importing cross_val_predict function
from sklearn.model_selection import cross_val_predict
#The predictions
pred = cross_val_predict(model, X_test, y_test)
pred

array([ 3.09396886e-01,  4.88879750e-01,  2.67869483e-01,  5.79169384e-02,
        5.95092105e-01,  3.70745503e-01,  1.91428339e-01,  4.08167861e-01,
        5.84481758e-01,  7.35896373e-01,  1.19214103e-02,  5.44499070e-01,
        5.10437728e-01,  5.42775958e-01,  3.50897631e-01, -8.60752568e-02,
        8.63214872e-01,  7.10327326e-01,  1.24348930e-01,  8.42107637e-01,
        4.50926809e-01, -3.30592012e-02,  3.54035368e-01,  1.82650667e-01,
        7.91765477e-01,  5.29344527e-01,  4.92771666e-01,  6.18937713e-01,
        4.20224704e-01,  3.79936839e-01, -7.35592091e-02,  5.28691684e-01,
        4.24248498e-01,  9.84545327e-02,  1.78191434e-01,  4.28101279e-01,
        6.33325305e-02,  2.30338227e-01,  6.24521397e-01,  2.66320681e-01,
        2.68642694e-01,  1.33659487e-01,  8.63666294e-01,  1.20933810e-01,
        3.64280426e-01,  5.45743941e-01,  3.58291611e-01, -3.34966655e-02,
        4.04085820e-01,  2.56140978e-01,  5.16607313e-01,  3.96531211e-01,
       -5.01147609e-02,  

In [17]:
#10-fodl CV on test data
scores_test = cross_val_score(model, X_test, y_test, cv=10)
scores_test

array([ 0.38046991,  0.27442836, -0.02122382,  0.15147421,  0.36515807,
        0.30358763,  0.34355002,  0.29798847,  0.3611689 , -0.07368638])

In [19]:
#The average score
print(np.mean(scores_test))

0.23829153705841516
